export const SOURCE_LANGUAGES = {
  de: 'alemán',
  ar: 'árabe',
  bg: 'búlgaro',
  cs: 'checo',
  zh: 'chino',
  ko: 'coreano',
  da: 'danés',
  sk: 'eslovaco',
  sl: 'esloveno',
  es: 'español',
  et: 'estonio',
  fi: 'finés',
  fr: 'francés',
  el: 'griego',
  hu: 'húngaro',
  id: 'indonesio',
  en: 'inglés',
  it: 'italiano',
  ja: 'japonés',
  lv: 'letón',
  lt: 'lituano',
  nl: 'neerlandés',
  nb: 'noruego',
  pl: 'polaco',
  pt: 'portugués',
  ro: 'rumano',
  ru: 'ruso',
  sv: 'sueco',
  tr: 'turco',
  uk: 'ucraniano',
}

export const TARGET_LANGUAGES = {
  de: 'alemán',
  ar: 'árabe',
  bg: 'búlgaro',
  cs: 'checo',
  zh: 'chino (simplificado)',
  ko: 'coreano',
  da: 'danés',
  sk: 'eslovaco',
  sl: 'esloveno',
  es: 'español',
  et: 'estonio',
  fi: 'finés',
  fr: 'francés',
  el: 'griego',
  hu: 'húngaro',
  id: 'indonesio',
  'en-US': 'inglés',
  it: 'italiano',
  ja: 'japonés',
  lv: 'letón',
  lt: 'lituano',
  nl: 'neerlandés',
  nb: 'noruego (bokmål)',
  pl: 'polaco',
  'pt-PT': 'portugués',
  ro: 'rumano',
  ru: 'ruso',
  sv: 'sueco',
  tr: 'turco',
  uk: 'ucraniano',
}

export const AUTO_LANGUAGE = 'auto'
